[Feature : kakao_login ] Create: kakaologinView
wecode-bootcamp-korea/32-2nd-Daengcance-backend pull request #3
Opened 2022-05-13 11:29 UTC by CHEESECHOUX

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- sns(kakao) 로그인 기능 구현 
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- sns(kakao) 로그인 기능 구현 
1. Front에서 건네준 카카오 token을 담아서 카카오한테 인증 요청
2. 유저가 맞다고 인증이 되면 카카오에서 유저 정보를 준다. 유저 정보(kakao id 등) 를 DB에 저장한다.
3. kakao_id가 DB에 있으면? 우리 서비스(웹 페이지)의 토큰 발급 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)
- 외부 API 사용법에 대해 알게 되었습니다. 
- 구현 하는 웹 페이지 상에서 kakao에서 준 kakao_id가 아닌 자체적으로 생성한 user의 id를 활용해야한다는 것을 알게 되었습니다. (보안상 이슈가 있을 수 있음.)

<br />

## :: 기타 질문 및 특이 사항

2022-05-15 06:43 UTC, Kang-kyunghun requested changes

2022-05-15 06:43 UTC, Kang-kyunghun commented on users/views.py
> +            kakao_user_response = requests.get(kakao_user_api, headers={'Authorization' : f'Bearer {kakao_access_token}'}).json()
requests 모듈을 사용할 때는 timeout 옵션을 꼭 부여해 주고 이에 대한 예외처리를 추가해 줘야합니다. 그래야 외부 api에 문제가 있을 때 우리의 서비스가 멈추는 것을 막을 수가 있습니다.

2022-05-15 06:43 UTC, Kang-kyunghun commented on users/views.py
> +                user = User.objects.get(kakao_id = kakao_id)
kakao_id의 존재 여부로 유저를 가입 시키는 로직 정말 잘 구현해 주셨습니다.
이대로 유지해도 좋지만, get_or_create를 적용해 볼 수 있으면 적용해 보는 것도 좋은 경험이 될 것 같습니다.

2022-05-15 06:43 UTC, Kang-kyunghun commented
리뷰 사항 적용해 주시고, 테스트 코드 추가해 주세요.

2022-05-16 06:06 UTC, CHEESECHOUX commented on users/views.py
> +            kakao_user_response = requests.get(kakao_user_api, headers={'Authorization' : f'Bearer {kakao_access_token}'}).json()
넵! 수정하겠습니다!

2022-05-18 05:00 UTC, CHEESECHOUX commented on users/views.py
> +                user = User.objects.get(kakao_id = kakao_id)
수정했습니다!

2022-05-18 05:00 UTC, CHEESECHOUX commented
test code 추가 했습니다!

2022-05-18 07:20 UTC, Kang-kyunghun commented
고생 많았습니다!!!

2022-05-18 07:20 UTC, merged